---
title: "Machine Learning Exam - Question 03"
author: "Darian Othman I6240624"
output: html_notebook
---
```{r, echo=FALSE}
setwd("C:/Users/I6240624/OneDrive/Courses/ML/Exam/ExamML")
```

```{r Libraries Import, echo=FALSE}
library(readr)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

```{r Data Import, message=FALSE, echo=FALSE}
df <- read_csv("data-1.csv")
# Reshape the data
df <- reshape(df,
idvar = c("Experiment","date","Day"),
timevar = "condition",
direction = "long",
varying = c("visitor_A",
"purchase_A",
"visitor_B",
"purchase_B"),
sep="_")
```

```{r, echo=FALSE}
ggplot(df, aes(x = Day, y = visitor, color = condition)) +
  geom_line() +
  facet_wrap(~Experiment) +
  labs(title = "Trend of the number of visitors per experiment", 
       x = "Instances (X)",
       y = "Number of visitors (N)") +
  theme(plot.title.position = "panel")
ggplot(df, aes(x = Day, y = purchase, color = condition)) +
  geom_line() +
  facet_wrap(~Experiment) +
  labs(title = "Trend of the number of purchases per experiment", 
       x = "Instances (X)",
       y = "Number of visitors (N)") +
  theme(plot.title.position = "panel")
```

```{r, echo=FALSE}
ggplot(df, aes(x = visitor, fill = condition)) +
  geom_histogram() +
  facet_wrap(~Experiment) +
  labs(title = "Distirbution (histogram) of the number of visitors per experiment", 
       x = "Number of visitors",
       y = "Frequency (Number of visitors)") +
  theme(plot.title.position = "panel")

ggplot(df, aes(x = condition, y = visitor, fill = condition)) +
  geom_boxplot() +
  facet_wrap(~Experiment) +
  labs(title = "Distirbution (boxplots) of the number of visitors per experiment", 
       x = "Condition",
       y = "Number of visitors (N)") +
  theme(plot.title.position = "panel")
```

```{r, echo=FALSE}
ggplot(df, aes(x = Day, y = purchase/visitor, color = condition)) +
  geom_line() +
  facet_wrap(~Experiment) +
  labs(title = "Trend of the number of Purchase Rate per experiment", 
       x = "Instances (X)",
       y = "Number of visitors (N)") +
  theme(plot.title.position = "panel")
```

```{r, message=FALSE, echo=FALSE}
for (i in 1:3){
  groupdf<-(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%group_by(condition)%>%summarise(sumvis=sum(visitor)))
  row1column1 <- as.numeric(groupdf[1,"sumvis"])
  row2column1 <- as.numeric(groupdf[2,"sumvis"])
  row1column2<- as.numeric(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%summarise(sumvis=sum(visitor)))
  row2column2 <- as.numeric(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%summarise(sumvis=sum(visitor)))
  
    # Create matrix
  testtable <- cbind(matrix(c(row1column1, row2column1, row1column2, row2column2),
                                 ncol = 2))
  
    # Perform Chi-square test
  csq_test <- chisq.test(testtable)
  
    # Result
  if (csq_test$p.value > 0.05){
    print("We fail to reject the null hypothesis that there is no significant difference between the total number of visitors across conditions within this experiment with at least 95% confidence.")
  } else {
    print("We reject the null hypothesis that there is no significant difference between the total number of visitors across conditions within this experiment with at least 95% confidence.")
          # Extract the total number of visitors per condition
  Exp_N <- as.data.frame(testtable[,1])
  colnames(Exp_N) <- "Total_N"
  Exp_N$condition <- c("Condition A", "Condition B")
  
    # Plot
  print(ggplot(Exp_N, aes(x = condition, y = Total_N, fill = condition)) +
    geom_col()+
    labs(title = paste("Total number of visitors per condition for experiment ",i, sep=""), 
         x = "Condition)",
         y = "Number of visitors (N)") +
    theme(plot.title.position = "panel"))
  }
}
```

```{r, echo=FALSE}
for (i in 1:3){
  groupdf<-(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%group_by(condition)%>%summarise(sumpur=sum(purchase)))
  row1column1 <- as.numeric(groupdf[1,"sumpur"])
  row2column1 <- as.numeric(groupdf[2,"sumpur"])
  row1column2<- as.numeric(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%summarise(sumpur=sum(purchase)))
  row2column2 <- as.numeric(df%>%filter(Experiment==paste("experiment",i,sep=""))%>%summarise(sumpur=sum(purchase)))
  
    # Create matrix
  testtable <- cbind(matrix(c(row1column1, row2column1, row1column2, row2column2),
                                 ncol = 2))
  
    # Perform Chi-square test
  csq_test <- chisq.test(testtable)
  
    # Result
  if (csq_test$p.value > 0.05){
    print("We fail to reject the null hypothesis that there is no significant difference between the total number of visitors across conditions within this experiment with at least 95% confidence.")
  } else {
    print("We reject the null hypothesis that there is no significant difference between the total number of visitors across conditions within this experiment with at least 95% confidence.")
          # Extract the total number of visitors per condition
  Exp_N <- as.data.frame(testtable[,1])
  colnames(Exp_N) <- "Total_N"
  Exp_N$condition <- c("Condition A", "Condition B")
  
    # Plot
  print(ggplot(Exp_N, aes(x = condition, y = Total_N, fill = condition)) +
    geom_col()+
    labs(title = paste("Total number of purchases per condition for experiment ",i, sep=""), 
         x = "Condition)",
         y = "Number of visitors (N)") +
    theme(plot.title.position = "panel"))
  }
}
```


```{r cummulative sum per conditions, echo=FALSE}
# Cummulative sum of number of visitors per conditions
    # Experiment 1
experiment1A <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["visitor"], FUN = cumsum)
experiment1B <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["visitor"], FUN = cumsum)
  # Experiment 2
experiment2A <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["visitor"], FUN = cumsum)
experiment2B <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["visitor"], FUN = cumsum)

  # Experiment 3
experiment3A <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["visitor"], FUN = cumsum)
experiment3B <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["visitor"], FUN = cumsum)

experiments<-cbind(experiment1A,experiment2A,experiment3A,experiment1B,experiment2B,experiment3B,df$Day)
colnames(experiments)<-c("experiment-1_A","experiment-2_A","experiment-3_A","experiment-1_B","experiment-2_B","experiment-3_B","Day")
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval<-data.frame(c(rep(0,length(df$Experiment))))
experimentspval$"p_exp-A" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_Exp1 <- experiments[i, "experiment-1_A"]
  row2column1_Exp1 <- experiments[i, "experiment-1_B"]
  row1column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  row2column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  
  testtable_Exp1 <- cbind(matrix(c(row1column1_Exp1, 
                                   row2column1_Exp1, 
                                   row1column2_Exp1, 
                                   row2column2_Exp1),
                                 ncol = 2))
  
  experimentspval$"p_exp-A"[i] <- chisq.test(testtable_Exp1)$p.value
}
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-B" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp2 <- experiments[i, "experiment-2_A"]
  row2column1_exp2 <- experiments[i, "experiment-2_B"]
  row1column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  row2column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  
  testtable_exp2 <- cbind(matrix(c(row1column1_exp2, 
                                   row2column1_exp2, 
                                   row1column2_exp2, 
                                   row2column2_exp2),
                                 ncol = 2))
  
  experimentspval$"p_exp-B"[i] <- chisq.test(testtable_exp2)$p.value
}
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-C" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp3 <- experiments[i, "experiment-3_A"]
  row2column1_exp3 <- experiments[i, "experiment-3_B"]
  row1column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  row2column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  
  testtable_exp3 <- cbind(matrix(c(row1column1_exp3, 
                                   row2column1_exp3, 
                                   row1column2_exp3, 
                                   row2column2_exp3),
                                 ncol = 2))
  
  experimentspval$"p_exp-C"[i] <- chisq.test(testtable_exp3)$p.value
}
```

```{r, warning=FALSE, echo=FALSE}
experimentspval<- cbind(experimentspval,Day=df$Day)
experimentspval <- select(experimentspval[1:30,], -1)
# Reshape the data
experimentspvals <- reshape(experimentspval,
                       timevar = "experiments",
                       direction = "long",
                       varying = c("p_exp-A","p_exp-B","p_exp-C"),
                       sep = "-")
experimentspvals<- select(experimentspvals,-id)
```

```{r, message=FALSE, echo=FALSE}
  # Plot
ggplot(experimentspvals, aes(x = Day, y = p_exp, color=experiments))+
  geom_line()+
  geom_line(aes(y = 0.05), color = "red", linetype = "dotted") +
  geom_text(aes(x = 1, y = 0.05, label = "alpha = 5%"), vjust = -2, hjust = 0, color = "black") +
  labs(title = "Statistical signifiance over time (number of visitors across conditions)", 
       x = "Instances (X)",
       y = "P-value")+
  theme(plot.title.position = "panel")
```



```{r cummulative sum per conditions, echo=FALSE}
# Cummulative sum of number of purchase per conditions
    # Experiment 1
experiment1A <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment1B <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["purchase"], FUN = cumsum)
  # Experiment 2
experiment2A <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment2B <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["purchase"], FUN = cumsum)

  # Experiment 3
experiment3A <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment3B <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["purchase"], FUN = cumsum)

experiments<-cbind(experiment1A,experiment2A,experiment3A,experiment1B,experiment2B,experiment3B,df$Day)
colnames(experiments)<-c("experiment-1_A","experiment-2_A","experiment-3_A","experiment-1_B","experiment-2_B","experiment-3_B","Day")
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval<-data.frame(c(rep(0,length(df$Experiment))))
experimentspval$"p_exp-A" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_Exp1 <- experiments[i, "experiment-1_A"]
  row2column1_Exp1 <- experiments[i, "experiment-1_B"]
  row1column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  row2column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  
  testtable_Exp1 <- cbind(matrix(c(row1column1_Exp1, 
                                   row2column1_Exp1, 
                                   row1column2_Exp1, 
                                   row2column2_Exp1),
                                 ncol = 2))
  
  experimentspval$"p_exp-A"[i] <- chisq.test(testtable_Exp1)$p.value
}
```

```{r Significance Over Time Purchase, warning=FALSE, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-B" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp2 <- experiments[i, "experiment-2_A"]
  row2column1_exp2 <- experiments[i, "experiment-2_B"]
  row1column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  row2column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  
  testtable_exp2 <- cbind(matrix(c(row1column1_exp2, 
                                   row2column1_exp2, 
                                   row1column2_exp2, 
                                   row2column2_exp2),
                                 ncol = 2))
  
  experimentspval$"p_exp-B"[i] <- chisq.test(testtable_exp2)$p.value
}
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-C" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp3 <- experiments[i, "experiment-3_A"]
  row2column1_exp3 <- experiments[i, "experiment-3_B"]
  row1column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  row2column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  
  testtable_exp3 <- cbind(matrix(c(row1column1_exp3, 
                                   row2column1_exp3, 
                                   row1column2_exp3, 
                                   row2column2_exp3),
                                 ncol = 2))
  
  experimentspval$"p_exp-C"[i] <- chisq.test(testtable_exp3)$p.value
}
```

```{r, warning=FALSE, echo=FALSE}
experimentspval<- cbind(experimentspval,Day=df$Day)
experimentspval <- select(experimentspval[1:30,], -1)
# Reshape the data
experimentspvals <- reshape(experimentspval,
                       timevar = "experiments",
                       direction = "long",
                       varying = c("p_exp-A","p_exp-B","p_exp-C"),
                       sep = "-")
experimentspvals<- select(experimentspvals,-id)
```

```{r, message=FALSE, echo=FALSE}
  # Plot
ggplot(experimentspvals, aes(x = Day, y = p_exp, color=experiments))+
  geom_line()+
  geom_line(aes(y = 0.05), color = "red", linetype = "dotted") +
  geom_text(aes(x = 1, y = 0.05, label = "alpha = 5%"), vjust = -2, hjust = 0, color = "black") +
  labs(title = "Statistical signifiance over time (number of visitors across conditions)", 
       x = "Instances (X)",
       y = "P-value")+
  theme(plot.title.position = "panel")
```


```{r, echo=FALSE}
  # Create matrix values
row1_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment1" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment1" & condition == "B"))["visitor"])))

row2_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment2" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment2" & condition == "B"))["visitor"])))

row3_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment3" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment3" & condition == "B"))["visitor"])))

row1_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3
row2_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3
row3_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3


  # Create matrix
testtable_across <- cbind(matrix(c(row1_column1, 
                            row2_column1, 
                            row3_column1, 
                            row1_column2, 
                            row2_column2, 
                            row3_column2),
                               ncol = 2))

  # Perform Chi-square test
csq_test_across <- chisq.test(testtable_across)

  # Result
if (csq_test_across$p.value > 0.05){
  print("We fail to reject the null hypothesis that there is no significant difference between the total number of visitors across experiments with at least 95% confidence.")
} else {
  print("We reject the null hypothesis that there is no significant difference between the total number of visitors across experiments with at least 95% confidence.")
}
df_testtable<-data.frame(testtable_across)
colnames(df_testtable)<-c("Actual Visitors", "Mean Visitors")
df_testtable$experiment<-c("Experiment 1", "Experiment 2", "Experiment 3")

df_testtable <- gather(df_testtable, key = "variable", value = "value", -experiment)

# Create the bar chart
print(ggplot(df_testtable, aes(x = experiment, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Actual VS Mean Amount of Visitors",
       x = "Experiments",
       y = "Number of Visitors",
       fill = "Variable") +
  theme_grey())

```


```{r, echo=FALSE}
  # Create matrix values
row1_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment1" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment1" & condition == "B"))["visitor"])))

row2_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment2" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment2" & condition == "B"))["visitor"])))

row3_column1 <- sum(c(sum((df %>% filter(Experiment == "experiment3" & condition == "A"))["visitor"]),sum((df %>% filter(Experiment == "experiment3" & condition == "B"))["visitor"])))

row1_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3
row2_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3
row3_column2 <- sum(c(row1_column1, row2_column1, row3_column1))/3


  # Create matrix
testtable_across <- cbind(matrix(c(row1_column1, 
                            row2_column1, 
                            row3_column1, 
                            row2_column1, 
                            row1_column1, 
                            row1_column1, 
                            row3_column1, 
                            row3_column1, 
                            row2_column1),
                               ncol = 3))

  # Perform Chi-square test
csq_test_across <- chisq.test(testtable_across)
csq_test_across
  # Result
if (csq_test_across$p.value > 0.05){
  print("We fail to reject the null hypothesis that there is no significant difference between the total number of visitors across experiments with at least 95% confidence.")
} else {
  print("We reject the null hypothesis that there is no significant difference between the total number of visitors across experiments with at least 95% confidence.")
}
df_testtable<-data.frame(Values=testtable_across[1,],Experiments=c("Experiment 1", "Experiment 2", "Experiment 3"))

# Create the bar chart
print(ggplot(df_testtable, aes(x = Experiments, y = Values, fill=Experiments)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Comparison of Visitor Amount Across Experiments",
       x = "Experiments",
       y = "Number of Visitors",
       fill = "Variable") +
  theme_grey())
testtable_across
```

```{r, echo=FALSE}
# Cummulative sum of number of visitors per conditions
    # Experiment 1
experiment1A <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment1B <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["purchase"], FUN = cumsum)
  # Experiment 2
experiment2A <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment2B <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["purchase"], FUN = cumsum)

  # Experiment 3
experiment3A <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["purchase"], FUN = cumsum)
experiment3B <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["purchase"], FUN = cumsum)

experiments<-cbind(experiment1A,experiment2A,experiment3A,experiment1B,experiment2B,experiment3B,df$Day)
colnames(experiments)<-c("experiment-1_A","experiment-2_A","experiment-3_A","experiment-1_B","experiment-2_B","experiment-3_B","Day")
```


```{r, echo=FALSE}
  # Prepare the data
experimentspval<-data.frame(c(rep(0,length(df$Experiment))))
experimentspval$"p_exp-A" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_Exp1 <- experiments[i, "experiment-1_A"]
  row2column1_Exp1 <- experiments[i, "experiment-1_B"]
  row1column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  row2column2_Exp1 <- mean(c(row1column1_Exp1, row2column1_Exp1))
  
  testtable_Exp1 <- cbind(matrix(c(row1column1_Exp1, 
                                   row2column1_Exp1, 
                                   row1column2_Exp1, 
                                   row2column2_Exp1),
                                 ncol = 2))
  
  experimentspval$"p_exp-A"[i] <- chisq.test(testtable_Exp1)$p.value
}
```

```{r, warning=FALSE, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-B" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp2 <- experiments[i, "experiment-2_A"]
  row2column1_exp2 <- experiments[i, "experiment-2_B"]
  row1column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  row2column2_exp2 <- mean(c(row1column1_exp2, row2column1_exp2))
  
  testtable_exp2 <- cbind(matrix(c(row1column1_exp2, 
                                   row2column1_exp2, 
                                   row1column2_exp2, 
                                   row2column2_exp2),
                                 ncol = 2))
  
  experimentspval$"p_exp-B"[i] <- chisq.test(testtable_exp2)$p.value
}
```

```{r, echo=FALSE}
  # Prepare the data
experimentspval$"p_exp-C" <- NA

  # Run the for loop
for (i in 1:nrow(experiments)){
  
  row1column1_exp3 <- experiments[i, "experiment-3_A"]
  row2column1_exp3 <- experiments[i, "experiment-3_B"]
  row1column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  row2column2_exp3 <- mean(c(row1column1_exp3, row2column1_exp3))
  
  testtable_exp3 <- cbind(matrix(c(row1column1_exp3, 
                                   row2column1_exp3, 
                                   row1column2_exp3, 
                                   row2column2_exp3),
                                 ncol = 2))
  
  experimentspval$"p_exp-C"[i] <- chisq.test(testtable_exp3)$p.value
}
```

```{r, warning=FALSE, echo=FALSE}
experimentspval<- cbind(experimentspval,Day=df$Day)
experimentspval <- select(experimentspval[1:30,], -1)
# Reshape the data
experimentspvals <- reshape(experimentspval,
                       timevar = "experiments",
                       direction = "long",
                       varying = c("p_exp-A","p_exp-B","p_exp-C"),
                       sep = "-")
experimentspvals<- select(experimentspvals,-id)
```

```{r, message=FALSE, echo=FALSE}
  # Plot
ggplot(experimentspvals, aes(x = Day, y = p_exp, color=experiments))+
  geom_line()+
  geom_line(aes(y = 0.05), color = "red", linetype = "dotted") +
  geom_text(aes(x = 1, y = 0.05, label = "alpha = 5%"), vjust = -2, hjust = 0, color = "black") +
  labs(title = "Statistical signifiance over time (Purchase Rate Across Experiments)", 
       x = "Instances (X)",
       y = "P-value")+
  theme(plot.title.position = "panel")
```




```{r, echo=FALSE}
  # Calcute the conversion rate for each experiment
convrate<-data.frame(c(rep(0,30)))
    # Experiment 1
Rate_1_A <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["visitor"], FUN = cumsum)

Rate_1_B <- ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["visitor"], FUN = cumsum)

    # Experiment 2
Rate_2_A <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["visitor"], FUN = cumsum)

Rate_2_B <- ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["visitor"], FUN = cumsum)

    # Experiment 3
Rate_3_A <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["visitor"], FUN = cumsum)

Rate_3_B <- ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["purchase"], FUN = cumsum) / ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["visitor"], FUN = cumsum)


  # Calculte the standard deviation for each experiment
    # Experiment 1
cSD_nclicks_1_A <- sqrt(Rate_1_A * (1 - Rate_1_A)/ ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="A"))["visitor"], FUN = cumsum))

cSD_nclicks_1_B <- sqrt(Rate_1_B * (1 - Rate_1_B)/ ave((df%>%filter(Experiment=="experiment1")%>%filter(condition=="B"))["visitor"], FUN = cumsum))

    # Experiment 2
cSD_nclicks_2_A <- sqrt(Rate_2_A * (1 - Rate_2_A)/ ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="A"))["visitor"], FUN = cumsum))

cSD_nclicks_2_B <- sqrt(Rate_2_B * (1 - Rate_2_B)/ ave((df%>%filter(Experiment=="experiment2")%>%filter(condition=="B"))["visitor"], FUN = cumsum))

    # Experiment 3
cSD_nclicks_3_A <- sqrt(Rate_3_A * (1 - Rate_3_A)/ ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="A"))["visitor"], FUN = cumsum))

cSD_nclicks_3_B <- sqrt(Rate_3_B * (1 - Rate_3_B)/ ave((df%>%filter(Experiment=="experiment3")%>%filter(condition=="B"))["visitor"], FUN = cumsum))

convrate<-cbind(convrate,Rate_1_A,Rate_1_B,Rate_2_A,Rate_2_B,Rate_3_A,Rate_3_B,cSD_nclicks_1_A,cSD_nclicks_1_B,cSD_nclicks_2_A,cSD_nclicks_2_B,cSD_nclicks_3_A,cSD_nclicks_3_B,experimentspval$Day)
colnames(convrate) <- c(0,"Rate-1_A","Rate-1_B","Rate-2_A","Rate-2_B","Rate-3_A","Rate-3_B","cSDnclicks-1_A","cSDnclicks-1_B","cSDnclicks-2_A","cSDnclicks-2_B","cSDnclicks-3_A","cSDnclicks-3_B","Day")
```

```{r, echo=FALSE}
convrate <- select(convrate[1:30,], -1)
```

```{r, echo=FALSE}
a <- reshape(convrate,
             idvar = c("Day"),
                       timevar = "condition",
                       direction = "long",
                       varying = c("Rate-1_A","Rate-1_B","Rate-2_A","Rate-2_B","Rate-3_A","Rate-3_B","cSDnclicks-1_A","cSDnclicks-1_B","cSDnclicks-2_A","cSDnclicks-2_B","cSDnclicks-3_A","cSDnclicks-3_B"),
                       sep = "_")
a <- reshape(a,
             idvar = c("Day","condition"),
                       timevar = "experiment",
                       direction = "long",
                       varying = c("Rate-1","Rate-2","Rate-3","cSDnclicks-1","cSDnclicks-2","cSDnclicks-3"),
                       sep = "-")
```

```{r, echo=FALSE}
ggplot(a, aes(x = Day, y = Rate, group = condition, fill = condition, color = condition)) +geom_line() +
  facet_grid(experiment ~ .) +
  geom_ribbon(aes(ymin = Rate - 1.96 * cSDnclicks, ymax = Rate + 1.96 * cSDnclicks)) +
  labs(title = "95% Confidence intervals of the conversion rate (nb clicks/nb visitors)", 
       x = "Instances (X)",
       y = "Conversion rate (%)") +
  theme(plot.title.position = "panel")
```
